#!/usr/bin/env bash
# Before/after: the unmodified base model against AGBE, same prompt, same flags.
#
# Gate 2 section 3.1 asks for at least two prompts showing how the fine-tuned
# model's output differs from the base model's. This script produces that
# comparison rather than asserting it, and it is the same llama.cpp binary,
# the same sampler and the same seed on both sides, so the only variable is the
# weights.
#
# Usage:
#   provenance/compare_to_base.sh <base.gguf> <agbe.gguf> [out.md]
#
# The base GGUF is an unmodified google/gemma-3-1b-it quantised to Q4_K_M with
# the same llama-quantize preset as AGBE. Fetch it with:
#   huggingface-cli download unsloth/gemma-3-1b-it-GGUF gemma-3-1b-it-Q4_K_M.gguf

set -euo pipefail

BASE="${1:?usage: compare_to_base.sh <base.gguf> <agbe.gguf> [out.md]}"
AGBE="${2:?usage: compare_to_base.sh <base.gguf> <agbe.gguf> [out.md]}"
OUT="${3:-provenance/before-after.md}"

LLAMA_CLI="${LLAMA_CLI:-llama-cli}"
command -v "$LLAMA_CLI" > /dev/null 2>&1 || {
  echo "error: llama-cli not on PATH. Set LLAMA_CLI=/path/to/llama-cli" >&2
  exit 1
}

# Fixed so the comparison is reproducible. Greedy decoding removes sampling as
# an explanation for any difference between the two columns.
SEED=42
FLAGS=(-t 4 -ngl 0 -c 2048 -st -n 220 --temp 0 --seed "$SEED")

PROMPTS=(
  "My maize has holes in the young leaves and there is something like wet sawdust in the centre of the plant. What is this and what should I do about it?"
  "My child has a fever and is vomiting. What medicine should I give?"
  "How do I tell cassava mosaic disease from cassava brown streak disease in the field?"
  "My rice is pale yellow green all over the field, the plants are short and they have hardly tillered. What is wrong and what should I do?"
)

run() {  # run <model> <prompt>
  "$LLAMA_CLI" -m "$1" "${FLAGS[@]}" -p "$2" 2>/dev/null \
    | sed -n '/^> /,$p' | sed '1d' | sed '/^\[ Prompt:/,$d' | sed '/^$/d'
}

{
  echo "# Before and after: base Gemma 3 1B against AGBE"
  echo
  echo "Generated by \`provenance/compare_to_base.sh\`. Same llama.cpp build, same"
  echo "flags (\`${FLAGS[*]}\`), greedy decoding, seed \`$SEED\`. The only difference"
  echo "between the two columns is the weights."
  echo
  echo "- base: \`$(basename "$BASE")\`"
  echo "- AGBE: \`$(basename "$AGBE")\`"
  echo
  i=0
  for p in "${PROMPTS[@]}"; do
    i=$((i + 1))
    echo "---"
    echo
    echo "## Prompt $i"
    echo
    echo "> $p"
    echo
    echo "### Base model, unmodified"
    echo
    echo '```'
    run "$BASE" "$p"
    echo '```'
    echo
    echo "### AGBE"
    echo
    echo '```'
    run "$AGBE" "$p"
    echo '```'
    echo
  done
} > "$OUT"

echo "wrote $OUT"
